name: Scan Code with Sonar

on:
  push:
    paths:
      - 'Dockerfile'
      - '**/*.go'
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  sonar:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # recommandé pour une meilleure pertinence d'analyse
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Optionnel : passer des paramètres ici si tu ne veux pas de fichier sonar-project.properties
        # with:
        #   args: >
        #     -Dsonar.organization=ton-org
        #     -Dsonar.projectKey=ton-projet
